language: csharp

sudo: required

branches:
  only:
    - master

matrix:
  include:
    - os: linux
      dotnet: 2.2.105
      mono: none
      dist: bionic
    - os: osx
      dotnet: 2.2.105
      mono: none
      osx_image: xcode8.3

script:
  - Tools/Travis/Build.sh