name: $(Date:yyyyMMdd.HHmm)

jobs:
- job: CheckNative
  pool:
    vmImage: vs2017-win2016
  steps:
  - powershell: ./CheckNative.ps1
    workingDirectory: Build
    displayName: 'CheckNative.ps1'
    name: checkNative
- job: Linux
  dependsOn: CheckNative
  condition: and(succeeded(), eq(dependencies.CheckNative.outputs['checkNative.BuildNative'], 'true'))
  pool:
    vmImage: Ubuntu 16.04
  steps:
  - template: Build/Linux/Build.yml