name: $(Date:yyyy.MM.dd.HHmm)

jobs:
- job: dotnet_windows
  displayName: Windows
  pool:
    vmImage: vs2017-win2016
  strategy:
    matrix:
      Q8-x86:
        QuantumName: Q8
        PlatformName: x86
      Q8-x64:
        QuantumName: Q8
        PlatformName: x64
      Q8-OpenMP-x64:
        QuantumName: Q8-OpenMP
        PlatformName: x64
      Q8-AnyCPU:
        QuantumName: Q8
        PlatformName: Any CPU
      Q16-x86:
        QuantumName: Q16
        PlatformName: x86
      Q16-x64:
        QuantumName: Q16
        PlatformName: x64
      Q16-OpenMP-x64:
        QuantumName: Q16-OpenMP
        PlatformName: x64
      Q16-AnyCPU:
        QuantumName: Q16
        PlatformName: Any CPU
      Q16-HDRI-x86:
        QuantumName: Q16-HDRI
        PlatformName: x86
      Q16-HDRI-x64:
        QuantumName: Q16-HDRI
        PlatformName: x64
      Q16-HDRI-OpenMP-x64:
        QuantumName: Q16-HDRI-OpenMP
        PlatformName: x64
      Q16-HDRI-AnyCPU:
        QuantumName: Q16-HDRI
        PlatformName: Any CPU
  steps:
    - template: build/windows/build.yml