name: $(Date:yyyyMMdd.HHmm)

jobs:
- job: Linux
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - bash: ./Check.sh
    workingDirectory: Build
    displayName: 'Linux/Check.sh'
  - template: Build/Linux/Build.yml
    condition: and(succeeded(), eq(variables['BuildLinux'], 'true'))